import type { NodeDefinition } from './nodeDefinitions.ts'

export const CSS_NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: 'css-selector',
    category: 'css',
    label: 'Selector',
    icon: '#',
    inputs: [],
    outputs: [{ id: 'selector', label: 'Selector', type: 'selector', direction: 'output' }],
    defaultParams: { selector: '.my-class' },
    paramMeta: { selector: { type: 'string', placeholder: '.my-class' } },
  },
  {
    type: 'css-color',
    category: 'css',
    label: 'Color',
    icon: '🎨',
    inputs: [
      { id: 'value', label: 'Value', type: 'color', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { value: '#000000', property: 'color' },
    paramMeta: { value: { type: 'color' }, property: { type: 'select', options: ['color', 'background-color', 'border-color', 'outline-color'] } },
  },
  {
    type: 'css-size',
    category: 'css',
    label: 'Size',
    icon: '📐',
    inputs: [
      { id: 'width', label: 'Width', type: 'string', direction: 'input' },
      { id: 'height', label: 'Height', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { width: '', height: '', unit: 'px' },
    paramMeta: { width: { type: 'string', placeholder: 'auto' }, height: { type: 'string', placeholder: 'auto' }, unit: { type: 'select', options: ['px', '%', 'vw', 'vh', 'em', 'rem'] } },
  },
  {
    type: 'css-spacing',
    category: 'css',
    label: 'Spacing',
    icon: '⊞',
    inputs: [],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { marginTop: '0', marginRight: '0', marginBottom: '0', marginLeft: '0', paddingTop: '0', paddingRight: '0', paddingBottom: '0', paddingLeft: '0' },
    paramMeta: { marginTop: { type: 'number' }, marginRight: { type: 'number' }, marginBottom: { type: 'number' }, marginLeft: { type: 'number' }, paddingTop: { type: 'number' }, paddingRight: { type: 'number' }, paddingBottom: { type: 'number' }, paddingLeft: { type: 'number' } },
  },
  {
    type: 'css-typography',
    category: 'css',
    label: 'Typography',
    icon: 'T',
    inputs: [
      { id: 'fontFamily', label: 'Font', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { fontSize: '16', fontFamily: '', fontWeight: '400', textAlign: 'left', lineHeight: '1.5' },
    paramMeta: { fontSize: { type: 'number' }, fontFamily: { type: 'string', placeholder: 'Arial' }, fontWeight: { type: 'select', options: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] }, textAlign: { type: 'select', options: ['left', 'center', 'right', 'justify'] }, lineHeight: { type: 'string', placeholder: '1.5' } },
  },
  {
    type: 'css-background',
    category: 'css',
    label: 'Background',
    icon: '◧',
    inputs: [
      { id: 'color', label: 'Color', type: 'color', direction: 'input' },
      { id: 'image', label: 'Image URL', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { bgColor: '#ffffff', gradient: '', image: '' },
    paramMeta: { bgColor: { type: 'color' }, gradient: { type: 'string', placeholder: 'linear-gradient(...)' }, image: { type: 'string', placeholder: 'url(...)' } },
  },
  {
    type: 'css-border',
    category: 'css',
    label: 'Border',
    icon: '▭',
    inputs: [
      { id: 'color', label: 'Color', type: 'color', direction: 'input' },
      { id: 'width', label: 'Width', type: 'number', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { width: '1', style: 'solid', color: '#d1d5db', radius: '0' },
    paramMeta: { width: { type: 'number' }, style: { type: 'select', options: ['solid', 'dashed', 'dotted', 'double', 'none'] }, color: { type: 'color' }, radius: { type: 'number' } },
  },
  {
    type: 'css-shadow',
    category: 'css',
    label: 'Shadow',
    icon: '☰',
    inputs: [
      { id: 'color', label: 'Color', type: 'color', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { x: '0', y: '2', blur: '4', spread: '0', color: 'rgba(0,0,0,0.1)', inset: false },
    paramMeta: { x: { type: 'number' }, y: { type: 'number' }, blur: { type: 'number' }, spread: { type: 'number' }, color: { type: 'color' }, inset: { type: 'boolean' } },
  },
  {
    type: 'css-flexbox',
    category: 'css',
    label: 'Flexbox',
    icon: '⇉',
    inputs: [],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { direction: 'row', wrap: 'nowrap', justify: 'flex-start', align: 'stretch', gap: '0' },
    paramMeta: { direction: { type: 'select', options: ['row', 'row-reverse', 'column', 'column-reverse'] }, wrap: { type: 'select', options: ['nowrap', 'wrap', 'wrap-reverse'] }, justify: { type: 'select', options: ['flex-start', 'center', 'flex-end', 'space-between', 'space-around', 'space-evenly'] }, align: { type: 'select', options: ['stretch', 'center', 'flex-start', 'flex-end', 'baseline'] }, gap: { type: 'number' } },
  },
  {
    type: 'css-grid',
    category: 'css',
    label: 'Grid',
    icon: '⊞',
    inputs: [],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { columns: '1fr', rows: 'auto', gap: '0', template: '' },
    paramMeta: { columns: { type: 'string', placeholder: '1fr 1fr' }, rows: { type: 'string', placeholder: 'auto' }, gap: { type: 'number' }, template: { type: 'string', placeholder: '"header header" "main aside"' } },
  },
  {
    type: 'css-transform',
    category: 'css',
    label: 'Transform',
    icon: '⟳',
    inputs: [],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { rotate: '0', scaleX: '1', scaleY: '1', translateX: '0', translateY: '0', skewX: '0', skewY: '0' },
    paramMeta: { rotate: { type: 'number' }, scaleX: { type: 'number' }, scaleY: { type: 'number' }, translateX: { type: 'number' }, translateY: { type: 'number' }, skewX: { type: 'number' }, skewY: { type: 'number' } },
  },
  {
    type: 'css-filter',
    category: 'css',
    label: 'Filter',
    icon: '◑',
    inputs: [],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { blur: '0', brightness: '100', contrast: '100', grayscale: '0', hue: '0' },
    paramMeta: { blur: { type: 'number' }, brightness: { type: 'number' }, contrast: { type: 'number' }, grayscale: { type: 'number' }, hue: { type: 'number' } },
  },
  {
    type: 'css-pseudo',
    category: 'css',
    label: 'Pseudo-class',
    icon: ':',
    inputs: [
      { id: 'selector', label: 'Selector', type: 'selector', direction: 'input' },
    ],
    outputs: [{ id: 'selector', label: 'Selector', type: 'selector', direction: 'output' }],
    defaultParams: { pseudo: 'hover', content: '' },
    paramMeta: { pseudo: { type: 'select', options: ['hover', 'focus', 'active', 'visited', 'before', 'after', 'first-child', 'last-child', 'nth-child'] }, content: { type: 'string', placeholder: 'attr(data-label)' } },
  },
  {
    type: 'css-media',
    category: 'css',
    label: 'Media Query',
    icon: '📱',
    inputs: [
      { id: 'selector', label: 'Selector', type: 'selector', direction: 'input' },
    ],
    outputs: [{ id: 'selector', label: 'Selector', type: 'selector', direction: 'output' }],
    defaultParams: { minWidth: '', maxWidth: '768', type: 'screen' },
    paramMeta: { minWidth: { type: 'string', placeholder: '768' }, maxWidth: { type: 'string', placeholder: '1024' }, type: { type: 'select', options: ['screen', 'print', 'all'] } },
  },
  {
    type: 'css-custom-prop',
    category: 'css',
    label: 'Custom Prop',
    icon: '--',
    inputs: [
      { id: 'value', label: 'Value', type: 'string', direction: 'input' },
      { id: 'name', label: 'Name', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { name: 'my-var', value: '#000' },
    paramMeta: { name: { type: 'string', placeholder: 'my-var' }, value: { type: 'string', placeholder: '#000' } },
  },
  {
    type: 'css-raw',
    category: 'css',
    label: 'Raw CSS',
    icon: '✎',
    inputs: [
      { id: 'code', label: 'Code', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { raw: '' },
    paramMeta: { raw: { type: 'string', placeholder: '/* CSS */' } },
  },
  {
    type: 'css-animation',
    category: 'css',
    label: 'Animation',
    icon: '▶',
    inputs: [
      { id: 'name', label: 'Name', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'css', label: 'CSS', type: 'css', direction: 'output' }],
    defaultParams: { name: 'fadeIn', duration: '0.3', timing: 'ease', delay: '0', iteration: '1', keyframes: 'from { opacity: 0; } to { opacity: 1; }' },
    paramMeta: { name: { type: 'string', placeholder: 'fadeIn' }, duration: { type: 'number' }, timing: { type: 'select', options: ['ease', 'linear', 'ease-in', 'ease-out', 'ease-in-out'] }, delay: { type: 'number' }, iteration: { type: 'string', placeholder: '1' }, keyframes: { type: 'string', placeholder: 'from {...} to {...}' } },
  },
]
