import type { NodeDefinition } from './nodeDefinitions.ts'

export const JS_NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: 'js-event',
    category: 'js',
    label: 'Event',
    icon: '⚡',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'selector', label: 'Selector', type: 'string', direction: 'input' },
    ],
    outputs: [
      { id: 'execOut', label: '', type: 'exec', direction: 'output' },
      { id: 'event', label: 'Event', type: 'string', direction: 'output' },
    ],
    defaultParams: { eventType: 'click', selector: '.btn' },
    paramMeta: { eventType: { type: 'select', options: ['click', 'dblclick', 'mouseenter', 'mouseleave', 'mousedown', 'mouseup', 'input', 'change', 'submit', 'focus', 'blur', 'keydown', 'keyup'] }, selector: { type: 'string', placeholder: '.btn' } },
  },
  {
    type: 'js-query',
    category: 'js',
    label: 'Query Selector',
    icon: '🔍',
    inputs: [
      { id: 'selector', label: 'Selector', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Element', type: 'string', direction: 'output' }],
    defaultParams: { selector: '.element', all: false },
    paramMeta: { selector: { type: 'string', placeholder: '.element' }, all: { type: 'boolean' } },
  },
  {
    type: 'js-get-attr',
    category: 'js',
    label: 'Get Attribute',
    icon: '👁',
    inputs: [
      { id: 'element', label: 'Element', type: 'string', direction: 'input' },
      { id: 'attr', label: 'Attr', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Value', type: 'string', direction: 'output' }],
    defaultParams: { attr: 'textContent' },
    paramMeta: { attr: { type: 'select', options: ['textContent', 'innerHTML', 'value', 'innerText', 'src', 'href', 'className', 'id', 'dataset'] } },
  },
  {
    type: 'js-set-attr',
    category: 'js',
    label: 'Set Attribute',
    icon: '✏',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'value', label: 'Value', type: 'string', direction: 'input' },
      { id: 'attr', label: 'Attr', type: 'string', direction: 'input' },
      { id: 'selector', label: 'Selector', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'execOut', label: '', type: 'exec', direction: 'output' }],
    defaultParams: { attr: 'textContent', selector: '.target' },
    paramMeta: { attr: { type: 'select', options: ['textContent', 'innerHTML', 'innerText', 'value', 'src', 'href', 'className', 'style', 'disabled', 'hidden'] }, selector: { type: 'string', placeholder: '.target' } },
  },
  {
    type: 'js-condition',
    category: 'js',
    label: 'Condition',
    icon: '◇',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'a', label: 'A', type: 'string', direction: 'input' },
      { id: 'b', label: 'B', type: 'string', direction: 'input' },
    ],
    outputs: [
      { id: 'execTrue', label: 'True', type: 'exec', direction: 'output' },
      { id: 'execFalse', label: 'False', type: 'exec', direction: 'output' },
      { id: 'result', label: 'Result', type: 'boolean', direction: 'output' },
    ],
    defaultParams: { operator: '===' },
    paramMeta: { operator: { type: 'select', options: ['===', '!==', '>', '<', '>=', '<=', 'includes', 'startsWith'] } },
  },
  {
    type: 'js-logic',
    category: 'js',
    label: 'Logic',
    icon: '∧',
    inputs: [
      { id: 'a', label: 'A', type: 'boolean', direction: 'input' },
      { id: 'b', label: 'B', type: 'boolean', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Result', type: 'boolean', direction: 'output' }],
    defaultParams: { op: 'AND' },
    paramMeta: { op: { type: 'select', options: ['AND', 'OR', 'NOT'] } },
  },
  {
    type: 'js-variable',
    category: 'js',
    label: 'Variable',
    icon: '✕',
    inputs: [
      { id: 'init', label: 'Init', type: 'string', direction: 'input' },
      { id: 'name', label: 'Name', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Value', type: 'string', direction: 'output' }],
    defaultParams: { name: 'myVar', kind: 'let', initValue: '0' },
    paramMeta: { name: { type: 'string', placeholder: 'myVar' }, kind: { type: 'select', options: ['let', 'const', 'var'] }, initValue: { type: 'string', placeholder: '0' } },
  },
  {
    type: 'js-math',
    category: 'js',
    label: 'Math',
    icon: '∑',
    inputs: [
      { id: 'a', label: 'A', type: 'number', direction: 'input' },
      { id: 'b', label: 'B', type: 'number', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Result', type: 'number', direction: 'output' }],
    defaultParams: { op: '+' },
    paramMeta: { op: { type: 'select', options: ['+', '-', '*', '/', '%', 'pow'] } },
  },
  {
    type: 'js-string',
    category: 'js',
    label: 'String',
    icon: 'Aa',
    inputs: [
      { id: 'a', label: 'A', type: 'string', direction: 'input' },
      { id: 'b', label: 'B', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Result', type: 'string', direction: 'output' }],
    defaultParams: { op: 'concat' },
    paramMeta: { op: { type: 'select', options: ['concat', 'template'] } },
  },
  {
    type: 'js-array',
    category: 'js',
    label: 'Array',
    icon: '[]',
    inputs: [
      { id: 'items', label: 'Items', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'value', label: 'Result', type: 'string', direction: 'output' }],
    defaultParams: { op: 'push', value: '' },
    paramMeta: { op: { type: 'select', options: ['push', 'pop', 'map', 'filter', 'length', 'join'] }, value: { type: 'string' } },
  },
  {
    type: 'js-console',
    category: 'js',
    label: 'Console',
    icon: '⎚',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'value', label: 'Value', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'execOut', label: '', type: 'exec', direction: 'output' }],
    defaultParams: { level: 'log' },
    paramMeta: { level: { type: 'select', options: ['log', 'warn', 'error', 'info', 'debug'] } },
  },
  {
    type: 'js-timer',
    category: 'js',
    label: 'Timer',
    icon: '⏱',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'ms', label: 'ms', type: 'number', direction: 'input' },
    ],
    outputs: [
      { id: 'execOut', label: '', type: 'exec', direction: 'output' },
      { id: 'timerId', label: 'Timer ID', type: 'number', direction: 'output' },
    ],
    defaultParams: { type: 'timeout', ms: '1000' },
    paramMeta: { type: { type: 'select', options: ['timeout', 'interval'] }, ms: { type: 'number' } },
  },
  {
    type: 'js-fetch',
    category: 'js',
    label: 'Fetch',
    icon: '🌐',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'url', label: 'URL', type: 'string', direction: 'input' },
      { id: 'body', label: 'Body', type: 'string', direction: 'input' },
    ],
    outputs: [
      { id: 'execOut', label: '', type: 'exec', direction: 'output' },
      { id: 'data', label: 'Data', type: 'string', direction: 'output' },
    ],
    defaultParams: { url: 'https://api.example.com/data', method: 'GET', body: '' },
    paramMeta: { url: { type: 'string', placeholder: 'https://...' }, method: { type: 'select', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] }, body: { type: 'string', placeholder: 'JSON body' } },
  },
  {
    type: 'js-dom-create',
    category: 'js',
    label: 'DOM Create',
    icon: '+',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'tag', label: 'Tag', type: 'string', direction: 'input' },
      { id: 'className', label: 'Class', type: 'string', direction: 'input' },
      { id: 'textContent', label: 'Text', type: 'string', direction: 'input' },
    ],
    outputs: [
      { id: 'execOut', label: '', type: 'exec', direction: 'output' },
      { id: 'element', label: 'Element', type: 'string', direction: 'output' },
    ],
    defaultParams: { tag: 'div', className: '', textContent: '' },
    paramMeta: { tag: { type: 'select', options: ['div', 'span', 'p', 'a', 'button', 'img', 'ul', 'li', 'section', 'article'] }, className: { type: 'string', placeholder: 'my-class' }, textContent: { type: 'string', placeholder: 'Hello' } },
  },
  {
    type: 'js-function',
    category: 'js',
    label: 'Function',
    icon: 'ƒ',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'name', label: 'Name', type: 'string', direction: 'input' },
      { id: 'params', label: 'Params', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'execOut', label: '', type: 'exec', direction: 'output' }],
    defaultParams: { name: 'myFunction', params: '', isAsync: false },
    paramMeta: { name: { type: 'string', placeholder: 'myFunction' }, params: { type: 'string', placeholder: 'a, b' }, isAsync: { type: 'boolean' } },
  },
  {
    type: 'js-return',
    category: 'js',
    label: 'Return',
    icon: '↩',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'value', label: 'Value', type: 'string', direction: 'input' },
    ],
    outputs: [],
    defaultParams: {},
  },
  {
    type: 'js-comment',
    category: 'js',
    label: 'Comment',
    icon: '//',
    inputs: [],
    outputs: [],
    defaultParams: { text: 'Comment' },
    paramMeta: { text: { type: 'string', placeholder: 'Comment' } },
  },
  {
    type: 'js-raw',
    category: 'js',
    label: 'Raw JS',
    icon: '✎',
    inputs: [
      { id: 'execIn', label: '', type: 'exec', direction: 'input' },
      { id: 'code', label: 'Code', type: 'string', direction: 'input' },
    ],
    outputs: [{ id: 'execOut', label: '', type: 'exec', direction: 'output' }],
    defaultParams: { code: '' },
    paramMeta: { code: { type: 'string', placeholder: '// JS code' } },
  },
]
